### ISSUE TITLE
Usage with react-native-navigation

### ISSUE THREAD

**Issue by smaris** [rauliyohmc/react-native-offline-utils#12]
When using this [react-native-navigation](https://github.com/wix/react-native-navigation) there is no root component, so I needed to wrap each screen. Or is there another way of doing this? 

```
export const registerScreens = () => {
  Navigation.registerComponent('Login', () => connect(mapStateToProps, mapDispatchToProps)(withNetworkConnectivity()(Login)), store, Provider)
  Navigation.registerComponent('Home', () => connect(mapStateToProps, mapDispatchToProps)(withNetworkConnectivity()(Home)), store, Provider)
}
```

There is an issue with the screen options that are not working anymore. I think statics are not passed within `withNetworkConnectivity`. Example:
```
export default class Home extends Component {
    static navigatorStyle = {
       tabBarHidden: true,
       navBarHidden: true
    }
    ...
}
```

**Comment by smaris** [comment]
Got it working by moving the screen options to the wrapping component:

```
const LoginComponent = withNetworkConnectivity()(Login)
LoginComponent.navigatorStyle = { tabBarHidden: true, navBarHidden: true }

Navigation.registerComponent('Login', () => connect(mapStateToProps, mapDispatchToProps)(LoginComponent), store, Provider)
```

But I should still have a root component, because now i'm setting listeners on all screens. State will be updated on connection change, so it will try to set state on screens that are unmounted. Any idea how to accomplish this with react-native-navigation?

**Comment by rauliyohmc** [comment]
Hi, thanks for submitting your issue.

I am actively working on a branch to release a new version of the library this week. 

First of all, if you wanna integrate the library with `redux` you need to pass `true` to `withNetworkConnectivity`, so it should be:

```
export const registerScreens = () => {
  Navigation.registerComponent('Login', () => connect(mapStateToProps, mapDispatchToProps)(withNetworkConnectivity(true)(Login)), store, Provider)
  Navigation.registerComponent('Home', () => connect(mapStateToProps, mapDispatchToProps)(withNetworkConnectivity(true)(Home)), store, Provider)
}
```

That way, the state is kept in the store and not passed down as a prop to your wrapped component.

In terms of statics hoisting, that would be fixed with the upcoming release, so you won't have to move the screen options to the wrapping component.

I haven't used react-native-navigation in any project so far, but based on the API it seems to me (at least for Android where I have some knowledge) every time you use `Navigation.registerComponent`, the library is creating a new Android activity underneath the hood, so you will have [different _root_ components depending on your active screen](https://github.com/wix/react-native-navigation/blob/master/src/Navigation.js#L82).

That being said, you don't have to worry about listeners. There will be only one at a time active.

I don't know the implementation details on iOS but I guess they should follow a similar approach where the React context is scoped to the active screen.

**Comment by felipemartim** [comment]
@rauliyohmc By wrapping up every screen, you end up doing HEAD requests on each navigation transition. Maybe the connectivity change logic could be managed by an event channel in redux-saga, so it could work without having a root component.

**Comment by dpellier** [comment]
Hi,

I'm trying to use the v4.x.x with [react-native-navigation](https://github.com/wix/react-native-navigation) and can't make the new `ReduxNetworkProvider` work.

Here is a simple example of what I'm trying to do
```
import { applyMiddleware, combineReducers, createStore } from 'redux';
import { Provider } from 'react-redux';
import { reducer as networkReducer } from 'react-native-offline';

const rootReducer = combineReducers({
    network: networkReducer
});
const store = createStore(rootReducer, applyMiddleware(thunk, logger));

// Registering the screen as described here https://wix.github.io/react-native-navigation/#/docs/top-level-api-migration?id=registering-screens-with-wrapping-provider-component
Navigation.registerComponent('Home', () => (props) => (
        <Provider store={ store }>
            <Home {...props} />
        </Provider>
    ), () => Home);
```

In my Home component, I can access the network `isConnected` value, though it is always true.
So I've tried to add the `ReduxNetworkProvider` with a `pingInterval` to check the connectivity.
```
import React, { Component } from 'react';
import { Text, View } from 'react-native';
import { ReduxNetworkProvider } from 'react-native-offline';
import { connect } from 'react-redux';

class Home extends Component {
    render() {
        return (
            <ReduxNetworkProvider pingInterval={3000}>
                <Text>You're { this.props.isOnline ? 'online' : 'offline' }</Text>
            </ReduxNetworkProvider>
        );
    }
}

function mapStateToProps({ network }) {
    return {
        isOnline: network.isConnected
    }
}
export default connect(mapStateToProps)(Home);
```

But then I get the following error:
<img width="361" alt="Screenshot 2019-04-16 at 11 18 59" src="https://user-images.githubusercontent.com/1390934/56197595-75f67800-6039-11e9-8f00-0e8aabc4b445.png">

It looks like the `ReduxNetworkProvider` is not a descendant of the react-redux <Provider> component.
Am I using it the wrong way?

Lib used:
```
"react": "16.8.3",
"react-native": "0.59.4",
"react-native-navigation": "2.17.0",
"react-native-offline": "4.3.1",
"react-redux": "7.0.2",
"redux": "4.0.1",
"redux-logger": "3.0.6",
"redux-thunk": "2.3.0"
```
